DROP TABLE IF EXISTS ip_block;
DROP TABLE IF EXISTS security_log;

CREATE TABLE security_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ip VARCHAR(50) NOT NULL,
    request_method VARCHAR(10) NOT NULL,
    request_path VARCHAR(2048),
    user_agent VARCHAR(1024),
    request_timestamp TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    attack_type VARCHAR(64),
    reason VARCHAR(2048),
    risk_score INT NOT NULL,
    ml_intrusion_probability DOUBLE NOT NULL,
    ml_intrusion_predicted BOOLEAN DEFAULT FALSE NOT NULL,
    is_suspicious BOOLEAN DEFAULT FALSE
);

CREATE TABLE ip_block (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ip VARCHAR(50) NOT NULL UNIQUE,
    blocked_until TIMESTAMP NOT NULL,
    reason VARCHAR(2048),
    created_at TIMESTAMP NOT NULL
);
